### ISSUE TITLE
loss when fcn converges

### ISSUE THREAD

**Issue by xjtuljy** [longjon/caffe#10]
Hi, 

I tried to build me own fcn, but it seems that loss I can get after fine tune is still around 1.1k for 512X384 images. So could anyone tell me the loss you got when the cnn converges?

Many thanks.

**Comment by joh17** [comment]
Hi, which FCN are you trying to train ?
We have the same problem in our team. We are trying to train FCN-8 on Pascal VOC 2012 dataset, but the loss stays extremely high and we have no clue why.
See the full description of the problem here : 
https://groups.google.com/d/msg/caffe-users/3eIMYV0OlY8/W-J1MQsvDgAJ

**Comment by xjtuljy** [comment]
Hi @joh17 , sorry I'm afraid I cannot help much, since I purely used C++ for training and prediction, as I need to integrate fcn into my own project. Actually I found that for our problem (binary segmentation, 512X384 image), when loss ~ 1.1k the training seems to be almost perfect already. Besides, I tried to use U-net (http://lmb.informatik.uni-freiburg.de/people/ronneber/u-net/) instead of FCN-8/16. In U-net the "fuse" layer is replaced by a Concatenate and a convolutional layer, which leads to better results in some cases according to my own experience.

**Comment by shelhamer** [comment]
Closing since the `future` branch is now deprecated; the relevant functionality has been merged to master.

Check out the [fcn.berkeleyvision.org repo](https://github.com/shelhamer/fcn.berkeleyvision.org) for master editions of the reference networks, weights, and code for learning, inference, and scoring.
