### ISSUE TITLE
Does this support cuDNN v4?

### ISSUE THREAD

**Issue by srika91** [longjon/caffe#12]
I would like to know does this repo supports cuDNN v4 as I am getting some errors as below

20 errors detected in the compilation of "/tmp/tmpxft_0000218a_00000000-16_cudnn_conv_layer.compute_50.cpp1.ii".
make: **\* [.build_release/cuda/src/caffe/layers/cudnn_conv_layer.o] Error 1

**Comment by shelhamer** [comment]
Closing since the `future` branch is now deprecated; the relevant functionality has been merged to master.

Check out the [fcn.berkeleyvision.org repo](https://github.com/shelhamer/fcn.berkeleyvision.org) for master editions of the reference networks, weights, and code for learning, inference, and scoring.
