### ISSUE TITLE
Is there any train_val networks of FCN-GoogleNet or any suggestion about it? Thank you.

### ISSUE THREAD

**Issue by justStarG** [longjon/caffe#14]

**Comment by shelhamer** [comment]
Closing since the `future` branch is now deprecated; the relevant functionality has been merged to master.

Check out the [fcn.berkeleyvision.org repo](https://github.com/shelhamer/fcn.berkeleyvision.org) for master editions of the reference networks, weights, and code for learning, inference, and scoring. While there is not a reference FCN-GoogLeNet, since we focused on accuracy with the FCN-VGG variants, we can try to include one after the NIPS deadline.

**Comment by justStarG** [comment]
Thank you.
