### ISSUE TITLE
Error in crop_layer.cpp

### ISSUE THREAD

**Issue by srika91** [longjon/caffe#15]
When I train FCN 32s for my own dataset ,i get the following error ,

(2 vs 3)
invalid crop parameters in dimension: 1

It points to line number 69 [here](https://github.com/BVLC/caffe/blob/master/src/caffe/layers/crop_layer.cpp)

This is happening at the crop layer.I cant understand this error.I resized all input images to 500x500(3 channel ) and labels are in 1xHxW and only two classes with 0 as background and 255 as foreground.

 When will such an error occur.I cannot understand the use of crop layer after deconvolution layer as well.Am i doing some mistake here,do I need to mention the crop_offset myself?

**Comment by shelhamer** [comment]
Closing since the `future` branch is now deprecated; the relevant functionality has been merged to master. Please ask modeling and usage questions about FCNs on the [caffe-users mailing list](https://groups.google.com/forum/#!forum/caffe-users).

Check out the [fcn.berkeleyvision.org repo](https://github.com/shelhamer/fcn.berkeleyvision.org) for master editions of the reference networks, weights, and code for learning, inference, and scoring.
