### ISSUE TITLE
Repeated loss of 3.04452

### ISSUE THREAD

**Issue by varunmurali1** [longjon/caffe#3]
Trying to use the FCN-Alexnet with the future branch. We get the same loss output with with different datasets, different input types etc. Have tried for 12,000 iterations with no change in the loss. Unsure as to what could be causing this. We get the exact same number every time.

**Comment by shelhamer** [comment]
Closing since the `future` branch is now deprecated; the relevant functionality has been merged to master. For modeling help with master see the [caffe-users mailing list](https://groups.google.com/forum/#!forum/caffe-users).

Check out the [fcn.berkeleyvision.org repo](https://github.com/shelhamer/fcn.berkeleyvision.org) for master editions of the reference networks, weights, and code for learning, inference, and scoring.

If you have the same, constant loss and/or score it is likely that the weights are not initialized properly and the network is outputting all zeroes.
