### ISSUE TITLE
k-channel implementation 

### ISSUE THREAD

**Issue by mtrth** [longjon/caffe#4]
My dataset has 2 classes; with 1000 training images of (5,256,256) also corresponding ground truth data (1,256,256) which is a binary image either 0 or 1 to represent the 2 classes.

In FCN-32 https://gist.github.com/shelhamer/80667189b218ad570e82  when training in solve.py you use the existing caffemodel which I assume is 3-channel ; but as I want to implement in on my 5 channel dataset can I use the same model provided ?

**Comment by r-kellermann** [comment]
@mtrth - this is impossible. You have to retrain the network from scratch. Also, since caffe currently supports 1 or 3 channel images only, you'll need to update this in deeper levels (See ReadImageToDatum to start with, https://github.com/BVLC/caffe/blob/master/src/caffe/util/io.cpp)

**Comment by shelhamer** [comment]
Closing since the `future` branch is now deprecated; the relevant functionality has been merged to master. For modeling help with master see the [caffe-users mailing list](https://groups.google.com/forum/#!forum/caffe-users).

Check out the [fcn.berkeleyvision.org repo](https://github.com/shelhamer/fcn.berkeleyvision.org) for master editions of the reference networks, weights, and code for learning, inference, and scoring.

@mtrth the `conv1` layer the PASCAL FCN-32s is 3 channel since it was learned from RGB images. However, you could initialize a 5 channel `conv1` by filling the 2 extra channels with duplicated or random weights. It is not uncommon to fine-tune to other modalities (like depth) from a color model.

@r-kellermann Caffe is not restricted to 1 or 3 channel images; only certain data formats are limited in that way. Loading the data through a Python data layer or HDF5 allows N-D data.
