### ISSUE TITLE
mnist examples not running and tests fail

### ISSUE THREAD

**Issue by mujtabahasan** [longjon/caffe#7]
I have installed this FCN branch of caffe. There is no issue in make and make test but make runtest fails for some tests in SGDsolver. I commented those tests and rests are running.
Also, when I do examples/mnist/train_mnist_autoencoder_adagrad.sh, it gets hanged and doesn't proceed beyond 
I0102 18:03:51.671083  3065 layer_factory.hpp:76] Creating layer data
I0102 18:03:51.671159  3065 net.cpp:111] Creating Layer data
I0102 18:03:51.671169  3065 net.cpp:434] data -> data
I have figured out where it is stopping. In net.cpp at line 153,
              layers_[layer_id]->SetUp(bottom_vecs_[layer_id], top_vecs_[layer_id]);
is being executed which calls Setup in layer.hpp line 71
       void SetUp(const vector<Blob<Dtype>_>& bottom,
      const vector<Blob<Dtype>_>& top)

In this function, I can't find it proceeding beyond line 75 which is 
         LayerSetUp(bottom, top);
Apparently LayerSetup is a virtual function, but I couldn't find it's implementation. When I comment this line, it breaks at the next line in Reshape..
F0102 18:12:52.731317  3652 split_layer.cpp:22] Check failed: count_ == top[i]->count() (0 vs. 1) 

Also, I have a K40C GPU and CUDA-6.5 on which I am running the master branch caffe.

**Comment by shelhamer** [comment]
Closing since the `future` branch is now deprecated; the relevant functionality has been merged to master. For installation help on master see the [caffe-users mailing list](https://groups.google.com/forum/#!forum/caffe-users).

Check out the [fcn.berkeleyvision.org repo](https://github.com/shelhamer/fcn.berkeleyvision.org) for master editions of the reference networks, weights, and code for learning, inference, and scoring.
