### ISSUE TITLE
How to evaluate the fcn-32 pascal caffemodel?

### ISSUE THREAD

**Issue by ayumiymk** [longjon/caffe#9]
when I want to evaluate this given caffemodel : fcn-32s pascal, you gives a mean I/U 64.0. But I tried several times, I can not get the same value. I tried the follow ways:
1. resize the test image to 500 x 500, and resize the groundtruth to 500 x 500 too, then I got mean I/U 64.3
2. resize the test image to 500 x 500, and get the predict result with size 500 x 500, then I crop it to the size of original image, then got the mean I/U 64.5
3. keep the size of image, and input it directly(reshape the caffemodel's input layer), get the predict image of original size, then got the mean I/U 64.9
so my question is, how to process the image to get the right mean I/U 64.0, or is there code to get it by the author?
what's more, I test it on seg11valid. 
can you help me, thank you.

**Comment by shelhamer** [comment]
Closing since the `future` branch is now deprecated; the relevant functionality has been merged to master.

Check out the [fcn.berkeleyvision.org repo](https://github.com/shelhamer/fcn.berkeleyvision.org) for master editions of the reference networks, weights, and code for learning, inference, and scoring.
